// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts


// prisma.config.ts
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Wenn PRISMA_PROD_URL existiert (auf Vercel), nimm die. Ansonsten nimm die normale DATABASE_URL (lokal).
    url: env("PRISMA_PROD_URL") ?? env("DATABASE_URL"),
  },
});