// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts


// prisma.config.ts
import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Optional: use production URL when present, otherwise require DATABASE_URL.
    url: process.env.PRISMA_PROD_URL || env("DATABASE_URL"),
  },
});
